apiVersion: v1
kind: Secret
metadata:
  name: grantnz-db-secret
type: Opaque
data:
  rdbms-password: "{Base64 password}"
---
apiVersion: v1
kind: Secret
metadata:
  name: grantnz-pri-secret
  namespace: grant-n-z
type: Opaque
data:
  grantnz-private.key: "{Base64 private key}"
---
apiVersion: v1
kind: Secret
metadata:
  name: grantnz-pub-secret
  namespace: grant-n-z
type: Opaque
data:
  grantnz-public.key: "Base64 public key"
