name: grant_n_z_ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: checkout
      uses: actions/checkout@v1
    - name: unit-test
      run: sh .github/script/unit-test.sh

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: checkout
      uses: actions/checkout@v1
    - name: output-coverage
      run: sh .github/script/test-converage.sh
    - name: coverage-to-lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
    - name: build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sh .github/script/build.sh

  bump-version:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: checkout
      uses: actions/checkout@v1
    - name: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
      run: sh .github/script/bump-version.sh
