name: grant_n_z_ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: checkout
      uses: actions/checkout@v1
    - name: unit-test
      run: sh .github/scripts/unit-test.sh

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: checkout
      uses: actions/checkout@v1
    - name: output-coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sh .github/scripts/test-converage.sh
    - name: build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: sh .github/scripts/build.sh
